name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  # 수동 시작 트리거: Actions 탭 > Workflows > Deploy to Ubuntu Server > Run workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start SSH agent and add key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
        ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST '
          # 포트 3000번을 사용 중인 프로세스를 종료
          if lsof -t -i:3000; then
            kill -9 $(lsof -t -i:3000)
          fi
        '
        rsync -avz --delete --exclude=.git -e "ssh -p $SSH_PORT" ./ $SSH_USERNAME@$SSH_HOST:/var/www/devwize-nextjs
        ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST '
          cd /var/www/devwize-nextjs &&
          rm -rf .next &&
          npm install &&
          npm run build &&
          pm2 restart nextjs || pm2 start npm --name "nextjs" -- start &&
          pm2 save &&
          pm2 startup systemd -u $SSH_USERNAME --hp /home/$SSH_USERNAME
        '

